# Generated by Django 3.2.5 on 2022-03-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20220307_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='bio',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
