# Generated by Django 3.2.5 on 2022-03-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_profiles_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
