# Generated by Django 3.2.5 on 2022-03-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_alter_profiles_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
